### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by jakoinc134** [VukkyLtd/VukkyBot#28]
**Describe the bug**
vukyk bot wont shut down!
**To Reproduce**
he wont shut down

**Expected behavior**
he is a zombie
**Screenshots**

**Some details to help me**
 - VukkyBot version: [e.g. 1.0.2]
my npm file isnt on my pc he is just jesus
**Additional context**
help

**Comment by nyakase** [comment]
OP forgot to run `npm stop`.
