### ISSUE TITLE
Counting sometimes thinks a number is wrong when it's right

### ISSUE THREAD

**Issue by nyakase** [VukkyLtd/VukkyBot#48]
we have absolutely no idea why this happens
![image](https://user-images.githubusercontent.com/46850780/101479727-f5456780-3952-11eb-9a41-0c2f7130c4d2.png)

**Comment by emilianya** [comment]
It even says afterwards that correct number was the number said

**Comment by jakoinc134** [comment]
bot broke!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by emilianya** [comment]
@jakoinc134 yes. we know. that is what the issue is.

**Comment by emilianya** [comment]
bumping up priority because it seems to be getting more and more common

**Comment by emilianya** [comment]
I think I might know what is happening here! Applying a fix asap

**Comment by emilianya** [comment]
#49 should fix this

**Comment by emilianya** [comment]
https://imgur.com/a/7RCVJs3

**Comment by emilianya** [comment]
Seems to have been fixed with the pull req
