### ISSUE TITLE
[BUG] Counting still breaks from messages starting with 0x

### ISSUE THREAD

**Issue by emilianya** [VukkyLtd/VukkyBot#71]
To reproduce:
say something starting with 0x, for example 0x3
-> Vukkybot will break

**Comment by emilianya** [comment]
After further experimenting it seems that unlike before counting v2 where it broke the bot now it just accepts hexadecimal 🤷

**Comment by nyakase** [comment]
test before reporting

**Comment by emilianya** [comment]
@Vukky123 ffs, I thought it had broken on the first test
